import cx_Oracle

# Nos conectamos como el usuario todo con password "123" al localhost y puerto 1521.
connection = cx_Oracle.connect("TODO", "123", "localhost:1521")
print("Database version:", connection.version)
cursor = connection.cursor()



# Una vez creada la tabla comenten esta sección de código, 
# porque si vuelven a ejecutar arrojara error ya que la base
# ya se encuentra creada.
# NOTA : esto para el ejemplo, en la tarea deben buscar como
# verificar que no ejecutan este comando si la tabla se 
# encuentra previamente creada
cursor.execute (
    """
        CREATE TABLE Persona (
            person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            first_name VARCHAR2(50) NOT NULL,
            last_name VARCHAR2(50) NOT NULL,
            PRIMARY KEY(person_id)
        )
    """
)


connection.close()
