import cx_Oracle

# Nos conectamos como el usuario todo con password "123" al localhost y puerto 1521.
connection = cx_Oracle.connect("TODO", "123", "localhost:1521")
print("Database version:", connection.version)
cursor = connection.cursor()

try:
    cursor.execute(
        """
        CREATE TABLE Persona (
            person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            first_name VARCHAR2(50) NOT NULL,
            last_name VARCHAR2(50) NOT NULL,
            PRIMARY KEY(person_id)
        )
    """
    )
    
regiones_archivo = open("RegionesComunas.csv", "r")
comunas_archivo = open("CasosConfirmadosPorComuna.csv", "r")
for linea_leida in regiones_archivo:
    NombreRegion, CodigoRegion, CodigoComuna = linea_leida.strip(
        "\n").split(",")
    print("result: ", NombreRegion)

for linea_leida in comunas_archivo:
    Comuna, CodigoComuna, Poblacion, CasosConfirmados = linea_leida.strip(
        "\n").split(",")

regiones_archivo.close()
comunas_archivo.close()

connection.close()



